import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full bg-slate-300 text-black flex gap-4 justify-center">
          <Link href={"/"} >Home</Link>
          <Link href={"/dashboard"} >Dashboard</Link>
          <Link href={"/transaction"} >Transactions</Link>
          <Link href={"/report"} >Reports</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
