import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHouse } from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed bg-secondary p-3 rounded-md text-black flex flex-col top-1/2 -translate-y-1/2 gap-4">

          <Link href={"/"} >
            <FontAwesomeIcon icon={faHouse} color="#BBF7D0" />
          </Link>
          <Link href={"/dashboard"} >Dashboard</Link>
          <Link href={"/transaction"} >Transactions</Link>
          <Link href={"/report"} >Reports</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
