import {  Blinker, Catamaran, Encode_Sans, Nunito_Sans, Plus_Jakarta_Sans, Quicksand, Roboto } from "next/font/google";
import "./globals.css";
import { AuthProviderContext } from "@/contexts/AuthContext";
import Navbar from "@/components/Navbars/Navbar";
import { ReactNode } from "react";
import MobileNavbar from "@/components/Navbars/MobileNavbar";

const catamaran = Catamaran({
  weight: "900",
  variable: '--font-catamaran',
  display: 'swap',
  subsets: ['latin']
});

const nunitoSans = Nunito_Sans({
  weight: "400",
  display: 'swap',
  variable: '--font-nunito-sans',
  subsets: ['latin']
})

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  // adjustFontFallback: false,
  variable: '--font-roboto'
  
})

export const metadata = {
  title: "Zaxch Finance",
  description: "Generated by create next app",
};

type PropsType = {
  children: ReactNode
}

export default function RootLayout({ children }: PropsType) {

  return (
    <html lang="en">
      <body className={` ${catamaran.variable} ${nunitoSans.variable} ${roboto.variable}`}>
        <AuthProviderContext>

          {/* <Navbar /> */}
          
          {children}
          <MobileNavbar />
        </AuthProviderContext>
      </body>
    </html>
  );
}