import { Archivo_Black, Black_Han_Sans, Blinker, Bree_Serif, Chivo, Encode_Sans, Lilita_One, Passion_One, Patua_One, Roboto } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import Navbar from "@/components/navbars/Navbar";

const lilitaOne = Lilita_One({
  subsets: ["latin"],
  variable: "--font-lilita-one",
  weight: "400",
  display: 'swap',
  adjustFontFallback: false
});

const patuaOne = Patua_One({
  subsets: ['latin'],
  variable: '--font-patua-one',
  weight: '400',
  display: 'swap',
  adjustFontFallback: false
})

const blinker = Blinker({
  weight: "800",
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  variable: '--font-blinker'
});

const encodeSans = Encode_Sans({
  weight: "800",
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  variable: '--font-encodeSans'
});

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  variable: '--font-roboto'
  
})

export const metadata = {
  title: "Zaxch Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${lilitaOne.variable} ${patuaOne.variable} ${blinker.variable} ${encodeSans.variable} ${roboto.variable}`}>
        <AuthProvider>

          <Navbar />
          
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}