import { Catamaran, Nunito_Sans, Roboto } from "next/font/google";
import "./globals.css";
import { AuthProviderContext } from "@/contexts/AuthContext";
import { ReactNode } from "react";
import ToastContainer from "@/components/systems/ToastContainer";
import MobileNavbar from "@/components/navbars/MobileNavbar";

const catamaran = Catamaran({
  weight: "900",
  variable: "--font-catamaran",
  display: "swap",
  subsets: ["latin"],
  adjustFontFallback: false,
});

const nunitoSans = Nunito_Sans({
  weight: "400",
  display: "swap",
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  adjustFontFallback: false,
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  adjustFontFallback: false,
});

export const metadata = {
  title: "Zaxch Finance",
  description: "Generated by create next app",
};

type PropsType = {
  children: ReactNode;
};

export default function RootLayout({ children }: PropsType) {
  return (
    <html lang="en">
      <body
        className={`bg-background ${catamaran.variable} ${nunitoSans.variable} ${roboto.variable}`}
      >
        <AuthProviderContext>
          {children}
          <ToastContainer />
          <MobileNavbar />
        </AuthProviderContext>
      </body>
    </html>
  );
}
