const financialAdvice = {
    expensesGreaterThanIncome: [
        "Track your spending to identify unnecessary expenses.",
        "Create a budget to limit overspending.",
        "Consider cutting back on luxury items.",
        "Avoid using credit cards for non-essential purchases.",
        "Focus on needs rather than wants.",
        "Look for discounts and promotions before buying.",
        "Find ways to reduce fixed costs like subscriptions or rent.",
        "Cook at home instead of eating out to save money.",
        "Consider taking on a part-time job to increase income.",
        "Prioritize paying off high-interest debt first.",
        "Avoid impulsive shopping and plan purchases ahead.",
        "Reassess your financial goals to align with current income.",
        "Use cash instead of cards to limit spending.",
        "Sell items you no longer use to generate extra cash.",
        "Limit entertainment expenses by opting for free activities.",
        "Switch to more affordable alternatives for recurring expenses.",
        "Set a monthly savings goal and stick to it.",
        "Avoid taking on new debt until finances are stable.",
        "Seek professional financial advice for better money management.",
        "Focus on building an emergency fund to cover future shortfalls.",
    ],
    incomeGreaterThanExpenses: [
        "Invest the surplus money to grow your wealth.",
        "Increase your savings for long-term security.",
        "Build an emergency fund for unexpected expenses.",
        "Consider paying off outstanding debts faster.",
        "Diversify your investments to minimize risks.",
        "Spend on self-improvement, such as learning new skills.",
        "Support charitable causes or help those in need.",
        "Upgrade essential tools or equipment for better productivity.",
        "Plan for retirement by contributing to a retirement account.",
        "Maintain a healthy balance between spending and saving.",
        "Reward yourself occasionally but avoid overspending.",
        "Review and adjust your financial goals regularly.",
        "Use the extra funds to start or grow a side business.",
        "Ensure you have adequate insurance coverage.",
        "Save for large purchases instead of taking on debt.",
        "Continue living below your means to sustain financial growth.",
        "Explore opportunities for passive income generation.",
        "Plan vacations or experiences within a reasonable budget.",
        "Donate to causes you are passionate about.",
        "Keep a financial journal to track how you use your surplus.",
    ]
};

export default financialAdvice;